model:
    type: cnn_0
    tpu: no
    save_path: ../out/model
    parameters:
          batch_size: 128
          epochs: 100
          learning_rate: 0.001
          beta_1: 0.9
          beta_2: 0.999
dataset:
    raw_path: ../dataset
    num_class: 10
feature_extraction:
    min_note: 0
    max_note: 127
    features:
data_augmentation:
    sample_size: 300
    num_samples_per_track: 60
